# Generated by Django 3.2.6 on 2021-08-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(through='actors.ActorMovie', to='movies.Movie'),
        ),
    ]
